package jstypes

var JSTypes = map[string]string{
	"bool":       "boolean",
	"byte":       "number",
	"time":       "time",
	"date":       "date",
	"datetime":   "datetime",
	"int8":       "integer",
	"int16":      "integer",
	"int32":      "integer",
	"int64":      "integer",
	"float32":    "number",
	"float64":    "number",
	"decimal":    "number",
	"string":     "string",
	"text":       "text",
	"binary":     "binary",
	"json":       "object",
	"xml":        "string",
	"bool[]":     "booleans",
	"date[]":     "dates",
	"time[]":     "times",
	"datetime[]": "datetimes",
	"int8[]":     "numbers",
	"int16[]":    "numbers",
	"int32[]":    "numbers",
	"int64[]":    "numbers",
	"float32[]":  "numbers",
	"float64[]":  "numbers",
	"decimal[]":  "numbers",
	"string[]":   "strings",
}
