package jstypes

var JSTypes = map[string]string{
	"bool":      "boolean",
	"byte":      "nummber",
	"time":      "time",
	"date":      "date",
	"datedate":  "datedate",
	"int8":      "integer",
	"int16":     "integer",
	"int32":     "integer",
	"int64":     "integer",
	"float32":   "number",
	"float64":   "number",
	"decimal":   "number",
	"string":    "string",
	"text":      "text",
	"binary":    "binary",
	"json":      "object",
	"xml":       "string",
	"bool[]":    "primitives",
	"int8[]":    "primitives",
	"int16[]":   "primitives",
	"int32[]":   "primitives",
	"int64[]":   "primitives",
	"float32[]": "primitives",
	"float64[]": "primitives",
	"decimal[]": "primitives",
	"string[]":  "primitives",
}
